package:
  name: lmfit
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../


build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}


requirements:
    build:
        - python
        - setuptools
        - numpy
        - scipy

    run:
        - python
        - numpy
        - scipy

test:
    imports:
        - lmfit

about:
    home: http://lmfit.github.io/lmfit-py/
    license: BSD
